### PR TITLE
Support Person payload

### PR DESCRIPTION
**Pull request by mkdabrowski**

### CODE REVIEW

**Comment by StrangeWill** [comment]
Welp that's the last time I trust the new Github merge resolution, sorry about your master branch, let me know if that caused any problems on your end (oh it totally did it includes the `IOptions<>` change...).

If it's a problem, feel free to reset the branch, force-push and I'll fix the conflict on my end in the 0.5.0 branch.

Also thanks for the contribution, I'll take a closer look at it this weekend and probably merge it. From a first look it looks good.

**Comment by StrangeWill** [comment]
A new test in 0.5.0 is failing due to this change, I'll probably pull this in and fix it on the staging branch though. 👍

**Comment by mkdabrowski** [comment]
Many thanks for looking into that. That's my first PR on GitHub so I've selected master by mistake. 
I'll look into 0.5.0 and try to work with that version locally first.

**Comment by StrangeWill** [comment]
Awesome, looks good to me. So I'll pull this in. 👍

**Pull request merged**
